modmap:
  - name: Global
    remap:
      # Num Comma -> Dot
      KpDot: Dot
      # Caps Lock -> Ctrl or Esc
      CapsLock:
        held: Ctrl_L
        alone: Esc

keymap:
  - name: Global
    exact_match: true
    remap:
      # § -> `
      Grave: Shift-Equal
      # ½ -> ~
      Shift-Grave: Alt_R-RightBrace
      # ¤ -> ^
      Shift-4: Shift-RightBrace
      # ´ -> \
      Equal: Alt_R-Minus
      # ` -> |
      Shift-Equal: Alt_R-102nd
      # AltGr o -> å
      Alt_R-O: LeftBrace
      # AltGr O -> Å
      Alt_R-Shift-O: Shift-LeftBrace
      # å -> [
      LeftBrace: Alt_R-8
      # Å -> {
      Shift-LeftBrace: Alt_R-7
      # ¨ -> ]
      RightBrace: Alt_R-9
      # ^ -> }
      Shift-RightBrace: Alt_R-0
      # Alt å -> Alt [
      Alt-LeftBrace: Alt_R-ALt-8
      # Alt ¨ -> Alt ]
      Alt-RightBrace: Alt_R-Alt-9
keypress_delay_ms: 4
